/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.devicebankframe;

import Business.EcoSystem;
import Business.Lab.DeviceBank;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Register_device;
import Business.WorkQueue.Register_device_Directory;
import Business.WorkQueue.request_device;
import Business.WorkQueue.request_device_directory;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayushi
 */
public class Doctor_request extends javax.swing.JPanel {

    private final JPanel container;
    private final UserAccount userAccount;
    private final EcoSystem ecosystem;

    /**
     * Creates new form Doctor_request
     */
    public Doctor_request(JPanel container,EcoSystem ecosystem,UserAccount userAccount) {
        initComponents();
        this.container=container;
        this.ecosystem=ecosystem;
        this.userAccount=userAccount;
        populate_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Status", "Device Type", "Units Requested"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(195, 233, 245));
        jButton1.setText("Process Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(195, 233, 245));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Process Request");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_new/Logo All Page .png"))); // NOI18N
        jLabel6.setText("E mail :");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jButton1)
                                .addGap(143, 143, 143)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel  t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
        int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
        System.out.println("id"+s);
        request_device_directory rbd=ecosystem.getRbd();
        ArrayList<request_device> ol=rbd.getarray();
        int u=ol.size();
        System.out.println("O1====> "+ol);
        DeviceBank bb=(DeviceBank)(userAccount);
        for(int i=0;i<u;i++)
        {
            request_device o=ol.get(i);
            if(s==o.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
            {
                if(o.getStatus().matches("In Progress"))
                {
                boolean r=check();
                if(r==false)
                {
                    o.setStatus("Cancled");
                     JOptionPane.showMessageDialog(null,"Inadequate Inventory");  
                    
                }
                else
                {
                    sub();
                    o.setStatus("Approved");
                     JOptionPane.showMessageDialog(null, "Request Approved!!");

                }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Wrong Move!!");  
                    
                
                }
                
            }
            
            }
        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Status","Device Type","Units requested"}));
        populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Select a Row!!"); 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel  t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
        int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
        System.out.println("id"+s);
        request_device_directory rbd=ecosystem.getRbd();
        ArrayList<request_device> ol=rbd.getarray();
        int u=ol.size();
        DeviceBank bb=(DeviceBank)(userAccount);
        for(int i=0;i<u;i++)
        {
            request_device o=ol.get(i);
            if(s==o.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
            {
                if(o.getStatus().matches("In Progress"))
                {
                    o.setStatus("Cancled");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Wrong Move!!");
                }
            }
        }
        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Status","Device Type","Units requested"}));
        populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Select a Row!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void sub()
    {
        request_device_directory rbd=ecosystem.getRbd();
        ArrayList<request_device> ol=rbd.getarray();
        int u=ol.size();
        DeviceBank bb=(DeviceBank)(userAccount);
        for(int i=0;i<u;i++)
        {
            request_device o=ol.get(i);
            String gj=o.getBlood_type();
                int a=o.getUnits();
                System.out.println(gj);
                System.out.println(a);
                Map<String,Integer> stock=bb.getHmap();  
                for (Map.Entry<String, Integer> set : stock.entrySet()) 
                {
                    System.out.println(set.getKey());
                    System.out.println(gj);
                    if(set.getKey().equals(gj))
                    {
                        int a1=set.getValue();
                        int b=a1-a;
                        set.setValue(b);
                        
                    }
                }
        }
               
        
    }
    public boolean check()
    {
        DefaultTableModel  t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
        System.out.println("id"+s);
        request_device_directory rbd=ecosystem.getRbd();
        ArrayList<request_device> ol=rbd.getarray();
        int u=ol.size();
        boolean r=false;
        DeviceBank bb=(DeviceBank)(userAccount);
        for(int i=0;i<u;i++)
        {
            request_device o=ol.get(i);
            if(s==o.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
            {
                
                String gj=o.getBlood_type();
                int a=o.getUnits();
                System.out.println("gj====> "+gj);
//                System.out.println(gj);
                System.out.println("a===== "+a);
                Map<String,Integer> stock=bb.getHmap();  
                System.out.println("Stock ------> "+stock);
                for (Map.Entry<String, Integer> set : stock.entrySet()) 
                {
                    System.out.println("set.getKey() ****> "+set.getKey());
                    System.out.println("gj ****> "+gj);
                    System.out.println("set.getValue() ***> "+set.getValue());
//                    if(set.getKey().contains(gj))
                    if(gj.contains(set.getKey()))
                    {
                        if(set.getValue()>a)
                        {
                            System.out.println("if1");
                            System.out.println(set.getValue());
                            r= true;
                            break;
                        }
                    }
		}
            }
        }
        
        return r;
        
    }
        public void populate_table()
    {
        request_device_directory rbd=ecosystem.getRbd();
        ArrayList<request_device> ol=rbd.getarray();
        int u=ol.size();
        System.out.println(u);
        for(int i=0;i<u;i++)
        {
            request_device o=ol.get(i);
            DeviceBank bb=(DeviceBank)(userAccount);
            System.out.println(o.getBlood_bank_name());
            System.out.println(bb.getName());
            if(o.getBlood_bank_name().matches(bb.getName()))
            {
                DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();
                String s1=String.valueOf(o.getId());    
                String s[]={s1,o.getFirst_name(),o.getStatus(),o.getBlood_type(),Integer.toString(o.getUnits())};
                t2.addRow(s);
            }
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
